import React, { useState } from 'react';
import { GitCompare, X, Play, Copy, ArrowRight, CheckCircle2, RefreshCw, Layers } from 'lucide-react';

interface SchemaDiffModalProps {
  isOpen: boolean;
  onClose: () => void;
  sourceEnv?: string;
  targetEnv?: string;
}

export const SchemaDiffModal: React.FC<SchemaDiffModalProps> = ({
  isOpen,
  onClose,
  sourceEnv = 'development_db',
  targetEnv = 'production_db_main',
}) => {
  const [diffResult] = useState({
    tablesAdded: ['analytics_events', 'feature_flags'],
    tablesRemoved: ['temp_user_backup'],
    columnsModified: [
      { table: 'users', change: 'ADD COLUMN bio VARCHAR(255) NULL' },
      { table: 'orders', change: 'ALTER COLUMN total_amount TYPE NUMERIC(12,2)' },
    ],
    generatedSql: `-- Schema Migration Diff: development_db -> production_db_main
-- Generated by DevDash Enterprise Sync Engine

ALTER TABLE users ADD COLUMN bio VARCHAR(255) NULL;
ALTER TABLE orders ALTER COLUMN total_amount TYPE NUMERIC(12,2);

CREATE TABLE analytics_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_name VARCHAR(100) NOT NULL,
  user_id BIGINT REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE feature_flags (
  flag_key VARCHAR(100) PRIMARY KEY,
  is_enabled BOOLEAN DEFAULT false,
  updated_at TIMESTAMP DEFAULT NOW()
);

DROP TABLE IF EXISTS temp_user_backup;`,
  });

  if (!isOpen) return null;

  const copySql = () => {
    navigator.clipboard.writeText(diffResult.generatedSql);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md animate-fadeIn select-none font-sans">
      <div className="bg-surface border border-border rounded-xl shadow-2xl w-[720px] h-[520px] max-w-[95vw] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-5 py-3.5 border-b border-border flex items-center justify-between bg-surface/90">
          <div className="flex items-center space-x-2 text-accent font-semibold text-sm">
            <GitCompare className="w-4 h-4" />
            <span className="text-text">Live Database Schema Diff & Migration Generator</span>
          </div>
          <button onClick={onClose} className="p-1 rounded text-textMuted hover:text-text hover:bg-surface2 transition-colors">
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Environments Comparison Bar */}
        <div className="p-3 bg-surface2/30 border-b border-border flex items-center justify-center space-x-4 text-xs font-mono">
          <span className="px-2.5 py-1 bg-surface border border-border rounded text-emerald-400 font-bold">{sourceEnv} (Source)</span>
          <ArrowRight className="w-4 h-4 text-textMuted" />
          <span className="px-2.5 py-1 bg-surface border border-border rounded text-amber-400 font-bold">{targetEnv} (Target)</span>
        </div>

        {/* Content */}
        <div className="flex-1 p-5 overflow-auto space-y-4 bg-base">
          {/* Summary Badges */}
          <div className="grid grid-cols-3 gap-3 text-xs">
            <div className="p-3 bg-emerald-500/10 border border-emerald-500/30 rounded-lg text-emerald-400">
              <span className="text-[10px] uppercase font-bold block">Tables Added</span>
              <strong className="text-base">{diffResult.tablesAdded.length}</strong>
              <div className="text-[10px] text-textMuted font-mono mt-1">{diffResult.tablesAdded.join(', ')}</div>
            </div>
            <div className="p-3 bg-amber-500/10 border border-amber-500/30 rounded-lg text-amber-400">
              <span className="text-[10px] uppercase font-bold block">Columns Altered</span>
              <strong className="text-base">{diffResult.columnsModified.length}</strong>
              <div className="text-[10px] text-textMuted font-mono mt-1">{diffResult.columnsModified.map((c) => c.table).join(', ')}</div>
            </div>
            <div className="p-3 bg-red-500/10 border border-red-500/30 rounded-lg text-red-400">
              <span className="text-[10px] uppercase font-bold block">Tables Dropped</span>
              <strong className="text-base">{diffResult.tablesRemoved.length}</strong>
              <div className="text-[10px] text-textMuted font-mono mt-1">{diffResult.tablesRemoved.join(', ')}</div>
            </div>
          </div>

          {/* Generated SQL DDL */}
          <div className="bg-surface border border-border rounded-xl overflow-hidden">
            <div className="px-4 py-2 bg-surface2/30 border-b border-border flex items-center justify-between">
              <span className="text-[10px] font-semibold text-textMuted uppercase tracking-wider font-mono">Generated Migration DDL Script</span>
              <button onClick={copySql} className="px-2 py-1 bg-surface2 hover:bg-surface2/80 text-text text-[11px] rounded transition-colors flex items-center space-x-1">
                <Copy className="w-3 h-3" />
                <span>Copy DDL</span>
              </button>
            </div>
            <pre className="p-4 font-mono text-xs text-accent whitespace-pre-wrap overflow-auto max-h-[220px]">
              {diffResult.generatedSql}
            </pre>
          </div>
        </div>

        {/* Footer */}
        <div className="px-5 py-3 bg-surface border-t border-border flex items-center justify-end space-x-2">
          <button onClick={onClose} className="px-3 py-1.5 rounded text-xs text-textMuted hover:text-text">Cancel</button>
          <button onClick={copySql} className="px-4 py-1.5 bg-accent hover:bg-accentHover text-white rounded text-xs font-semibold shadow">
            Copy & Apply Migration
          </button>
        </div>
      </div>
    </div>
  );
};
